name: mybinder-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11.7
  - numpy=1.26.4
  - pandas=2.1.4
  - matplotlib=3.8.0
  - tensorflow=2.15.0
  - keras=2.15.0
  - sklearn=1.2.2
